### ISSUE TITLE
Add filetype or name exclusions

### ISSUE THREAD

**Issue by faun** [ggilder/bitrot#3]
Prevent the application from generating checksums for .DS_Store files or similar by adding builtin exclusions. Perhaps adding a configuration file format to the home directory would make this configurable globally. Additionally adding the ability using a command line flag to exclude a filetype, directory or regular expression pattern.

**Comment by ggilder** [comment]
TODO:
- [x] Add ability to exclude file/folder names
- [ ] Add a default list of exclusions
- [ ] Make the setting configurable with a dotfile
- [ ] Make the setting configurable with a command-line flag

**Comment by ggilder** [comment]
Marking this done; moved remaining lower-priority tasks to separate issues
